board: ["nice_nano"]
shield: ["alitbkmini_left", "alitbkmini_right", "alitbkmini_test"]
include:
  - board: nice_nano
    shield: "alitbkmini_left"
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: "alitbkmini_right"
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: "alitbkmini_test"
    snippet: zmk-usb-logging
